schema_version: "1.0"
id: 40karmoury
display_name: Warhammer 40K Imperial Armoury
short_description: >-
  Adds Imperial weapons from the Warhammer 40K universe. It was originally made
  by Wulfle, or so the modinfo says.
description: >-
  Adds Imperial weapons from the Warhammer 40K universe. It was originally made
  by Wulfle, or so the modinfo says.
author:
  - Kingcat
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/kingcet/WH40K-Imperial-Armoury/tree/main/WH_40K_Imperial_Armoury
version: 2026.6.16-f863f21
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-05-16T09:24:23.160Z"
  - version: 2026.6.8-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-08T03:02:25.640Z"
  - version: 2026.6.9-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-09T02:39:14.166Z"
  - version: 2026.6.10-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-10T02:55:57.155Z"
  - version: 2026.6.11-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-11T02:58:55.892Z"
  - version: 2026.6.12-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-12T03:01:50.333Z"
  - version: 2026.6.13-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-13T02:49:09.194Z"
  - version: 2026.6.14-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-14T02:59:41.654Z"
  - version: 2026.6.15-f863f21
    source:
      type: github_archive
      url: >-
        https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
      commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
      extract_path: WH_40K_Imperial_Armoury
    released_at: "2026-06-15T03:32:51.641Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/kingcet/WH40K-Imperial-Armoury/archive/refs/heads/main.zip
  commit_sha: f863f21df6a9b72bc1287a28cf8885c8aeeeddc2
  extract_path: WH_40K_Imperial_Armoury
categories:
  - items
modinfo_url: >-
  https://raw.githubusercontent.com/kingcet/WH40K-Imperial-Armoury/f863f21df6a9b72bc1287a28cf8885c8aeeeddc2/WH_40K_Imperial_Armoury/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-16T03:34:53.271Z"
