schema_version: "1.0"
id: afs_easydocs
display_name: Aftershock - Easydocs
short_description: Makes all Autodocs in Aftershock safe
author:
  - Relgar
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Relgar/AFS_Easydocs/tree/main/AFS_Easydocs"
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
  commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
  extract_path: AFS_Easydocs
description: Makes all Autodocs in Aftershock safe
categories:
  - rebalance
dependencies:
  bn: ">=0.9.1"
  aftershock: "*"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:24:28.541Z"
