schema_version: "1.0"
id: afs_easydocs
display_name: Aftershock - Easydocs
short_description: Makes all Autodocs in Aftershock safe
description: Makes all Autodocs in Aftershock safe
author:
  - Relgar
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Relgar/AFS_Easydocs/tree/main/AFS_Easydocs"
version: 2026.6.19-922a8a1
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-05-16T09:24:28.541Z"
  - version: 2026.6.8-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-08T03:02:24.253Z"
  - version: 2026.6.9-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-09T02:39:12.946Z"
  - version: 2026.6.10-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-10T02:55:42.075Z"
  - version: 2026.6.11-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-11T02:58:13.268Z"
  - version: 2026.6.12-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-12T03:01:28.600Z"
  - version: 2026.6.13-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-13T02:48:48.273Z"
  - version: 2026.6.14-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-14T02:59:03.385Z"
  - version: 2026.6.15-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-15T03:32:37.295Z"
  - version: 2026.6.16-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-16T03:34:31.951Z"
  - version: 2026.6.17-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-17T03:26:35.273Z"
  - version: 2026.6.18-922a8a1
    source:
      type: github_archive
      url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
      commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
      extract_path: AFS_Easydocs
    released_at: "2026-06-18T03:01:22.045Z"
dependencies:
  bn: ">=0.9.1"
  aftershock: "*"
source:
  type: github_archive
  url: "https://github.com/Relgar/AFS_Easydocs/archive/refs/heads/main.zip"
  commit_sha: 922a8a19214466d05de7133070892ff3f90e5bc8
  extract_path: AFS_Easydocs
categories:
  - rebalance
modinfo_url: >-
  https://raw.githubusercontent.com/Relgar/AFS_Easydocs/922a8a19214466d05de7133070892ff3f90e5bc8/AFS_Easydocs/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-19T03:55:49.471Z"
