schema_version: "1.0"
id: arcana_crit_patch
display_name: Arcana/C.R.I.T. Patchmod
short_description: >-
  Optional patch mod that allows content in Arcana and C.R.I.T. to interact with
  each other.
author:
  - Chaosvolt
license: CC-BY-SA-3.0
homepage: >-
  https://github.com/chaosvolt/cdda-arcana-mod/tree/master/Patchmods/BN_Arcana_Crit_Patch
version: 2026.6.16-33bfbbe
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 37718985431bdbfbee1488e23747edbed3440cbf
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2025-12-08T17:38:23.168Z"
  - version: 2026.6.8-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-08T03:02:40.847Z"
  - version: 2026.6.9-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-09T02:39:30.554Z"
  - version: 2026.6.10-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-10T02:55:39.354Z"
  - version: 2026.6.11-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-11T02:58:04.691Z"
  - version: 2026.6.12-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-12T03:01:24.073Z"
  - version: 2026.6.13-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-13T02:48:44.325Z"
  - version: 2026.6.14-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-14T02:58:55.830Z"
  - version: 2026.6.15-33bfbbe
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip
      commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
      extract_path: Patchmods/BN_Arcana_Crit_Patch
    released_at: "2026-06-15T03:32:34.629Z"
yanked:
  reason: "Mainlined in Cataclysm: Bright Nights."
dependencies:
  bn: ">=0.9.1"
  arcana: "*"
  crt_expansion: "*"
source:
  type: github_archive
  url: "https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip"
  commit_sha: 33bfbbe31cd95575636443b13183e127e19e36d0
  extract_path: Patchmods/BN_Arcana_Crit_Patch
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/chaosvolt/cdda-arcana-mod/37718985431bdbfbee1488e23747edbed3440cbf/Patchmods/BN_Arcana_Crit_Patch/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: master
parent: arcana
last_updated: "2026-06-16T03:34:27.942Z"
