schema_version: "1.0"
id: birdbox_mod
display_name: Birdbox
short_description: >-
  Adds a monster that will drive you insane, and cause death upon seeing it.
  Always keep a blindfold on hand, and have a plan to break line of sight.
author:
  - Kota
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/shmakota/birdbox_mod_bn/tree/main/birdbox"
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/shmakota/birdbox_mod_bn/archive/refs/heads/main.zip"
  commit_sha: b3ac37c1c9be11cbc7e91012d29bc92401d9b927
  extract_path: birdbox
description: >-
  Adds a monster that will drive you insane, and cause death upon seeing it.
  Always keep a blindfold on hand, and have a plan to break line of sight.
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:25:26.894Z"
