schema_version: "1.0"
id: blazemod_szq_edit
display_name: Blazemod SzQ edit
short_description: A lot of vehicle parts and weapons.json
description: A lot of vehicle parts and weapons.json
author:
  - Blaze-whatdoyoumeanitsalreadytaken
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/SzQ1/blazemod-SzQ-edit"
version: 2026.6.8-b4b8ded
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/SzQ1/blazemod-SzQ-edit/archive/refs/heads/main.zip"
  commit_sha: b4b8ded0c6dd3e605d26766f5179d0e5a2a3362e
categories:
  - vehicles
modinfo_url: >-
  https://raw.githubusercontent.com/SzQ1/blazemod-SzQ-edit/b4b8ded0c6dd3e605d26766f5179d0e5a2a3362e/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-08T03:03:01.360Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/SzQ1/blazemod-SzQ-edit/archive/refs/heads/main.zip"
      commit_sha: b4b8ded0c6dd3e605d26766f5179d0e5a2a3362e
    released_at: "2026-05-16T09:24:17.781Z"
