schema_version: "1.0"
id: cata
display_name: Cataclysm++
short_description: >-
  The unofficial expansion mod for Cataclysm: Bright Nights.


  The gigantic jabberwock of a mod that adds a lot of content to the game: new
  items, buildings, scenarios, monsters, etc. It also reworks and
description: >-
  The unofficial expansion mod for Cataclysm: Bright Nights.


  The gigantic jabberwock of a mod that adds a lot of content to the game: new
  items, buildings, scenarios, monsters, etc. It also reworks and adds
  alternatives to many things from recipes to scenarios. It also adds a
  pseudo-story and lore on the works.


  The Bio-Weapon, Super Soldier, Commandeers, Slave Fighters and the Old World
  Prepper NPC factions join the world.


  Seek the Bio-weapons, find loot, take down new monsters and invest in skills
  for new craftable items.
author:
  - Noctifer
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Noctifer-de-Mortem/nocts_cata_mod/tree/master/nocts_cata_mod_BN
version: 2026.6.18-5b3e539
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 640477a78597002ffbaa2c9bf52bf3a11edd8c59
      extract_path: nocts_cata_mod_BN
    released_at: "2026-05-16T09:24:12.316Z"
  - version: 2026.6.8-94b18c2
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 94b18c22b5770c1ab79034c16bceb722dbeeaac1
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-08T03:03:01.978Z"
  - version: 2026.6.9-81d5d98
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 81d5d98f1cf97f2a442343914a2c7a35655ffee6
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-09T02:39:53.408Z"
  - version: 2026.6.10-81d5d98
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 81d5d98f1cf97f2a442343914a2c7a35655ffee6
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-10T02:55:53.596Z"
  - version: 2026.6.11-81d5d98
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 81d5d98f1cf97f2a442343914a2c7a35655ffee6
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-11T02:58:44.345Z"
  - version: 2026.6.12-81d5d98
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 81d5d98f1cf97f2a442343914a2c7a35655ffee6
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-12T03:01:44.842Z"
  - version: 2026.6.13-f9c9b0e
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: f9c9b0e22c7a7e8b26e506017eed71192aede2f0
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-13T02:49:03.662Z"
  - version: 2026.6.14-25c6328
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 25c63285e2de3407513f04b2ad6ec589bf8fb39f
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-14T02:59:31.722Z"
  - version: 2026.6.15-25c6328
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 25c63285e2de3407513f04b2ad6ec589bf8fb39f
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-15T03:32:48.184Z"
  - version: 2026.6.16-b22291f
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: b22291ffb57d5f7ee935ed3c214a0931b98d14e6
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-16T03:34:48.067Z"
  - version: 2026.6.17-5b3e539
    source:
      type: github_archive
      url: >-
        https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
      commit_sha: 5b3e539dcbee962526c11aab5bc6177b10a4bf5a
      extract_path: nocts_cata_mod_BN
    released_at: "2026-06-17T03:26:47.033Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/refs/heads/master.zip
  commit_sha: 5b3e539dcbee962526c11aab5bc6177b10a4bf5a
  extract_path: nocts_cata_mod_BN
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/Noctifer-de-Mortem/nocts_cata_mod/640477a78597002ffbaa2c9bf52bf3a11edd8c59/nocts_cata_mod_BN/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: master
last_updated: "2026-06-18T03:01:47.797Z"
