schema_version: "1.0"
id: chorus_weapons
display_name: Chorus's Gear
short_description: >-
  Edits and additions to weaponry, mostly to personal preference and as a
  learning tool.
description: >-
  Edits and additions to weaponry, mostly to personal preference and as a
  learning tool.
author:
  - ChorusSystem
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/yay855/ChorusMod/tree/main/Chorus Gear"
version: 2026.6.18-9ba39b3
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-05-16T09:24:48.905Z"
  - version: 2026.6.8-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-08T03:02:59.829Z"
  - version: 2026.6.9-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-09T02:39:51.274Z"
  - version: 2026.6.10-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-10T02:55:36.856Z"
  - version: 2026.6.11-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-11T02:57:58.236Z"
  - version: 2026.6.12-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-12T03:01:20.433Z"
  - version: 2026.6.13-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-13T02:48:40.990Z"
  - version: 2026.6.14-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-14T02:58:49.691Z"
  - version: 2026.6.15-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-15T03:32:32.067Z"
  - version: 2026.6.16-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Gear
    released_at: "2026-06-16T03:34:24.544Z"
  - version: 2026.6.17-9ba39b3
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
      extract_path: Chorus Gear
    released_at: "2026-06-17T03:26:29.469Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
  commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
  extract_path: Chorus Gear
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/yay855/ChorusMod/77f71e190c6bb430da393eb06ee49f336221715e/Chorus%20Gear/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-18T03:01:09.154Z"
