schema_version: "1.0"
id: chorus_cbms
display_name: Chorus's CBMs
short_description: >-
  Edits and additions to CBM content, mostly to personal preference and as a
  learning tool.
author:
  - ChorusSystem
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/yay855/ChorusMod/tree/main/Chorus CBMs"
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
  commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
  extract_path: Chorus CBMs
description: >-
  Edits and additions to CBM content, mostly to personal preference and as a
  learning tool.
categories:
  - content
dependencies:
  bn: ">=0.9.1"
  chorus_weapons: "*"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:24:48.905Z"
