schema_version: "1.0"
id: chorus_arcana_addon
display_name: Chorus's Arcana Addon
short_description: "Various things added to Arcana, some pulled from other mods."
description: "Various things added to Arcana, some pulled from other mods."
author:
  - ChorusSystem
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/yay855/ChorusMod/tree/main/Chorus Arcana Addon"
version: 2026.6.20-9ba39b3
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-05-16T09:24:48.905Z"
  - version: 2026.6.8-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-08T03:02:50.024Z"
  - version: 2026.6.9-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-09T02:39:40.801Z"
  - version: 2026.6.10-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-10T02:55:39.369Z"
  - version: 2026.6.11-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-11T02:58:04.851Z"
  - version: 2026.6.12-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-12T03:01:24.112Z"
  - version: 2026.6.13-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-13T02:48:44.362Z"
  - version: 2026.6.14-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-14T02:58:55.955Z"
  - version: 2026.6.15-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-15T03:32:34.636Z"
  - version: 2026.6.16-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-16T03:34:27.989Z"
  - version: 2026.6.17-9ba39b3
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-17T03:26:32.547Z"
  - version: 2026.6.18-9ba39b3
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-18T03:01:15.065Z"
  - version: 2026.6.19-9ba39b3
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
      extract_path: Chorus Arcana Addon
    released_at: "2026-06-19T03:55:42.423Z"
dependencies:
  bn: ">=0.9.1"
  arcana: "*"
source:
  type: github_archive
  url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
  commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
  extract_path: Chorus Arcana Addon
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/yay855/ChorusMod/77f71e190c6bb430da393eb06ee49f336221715e/Chorus%20Arcana%20Addon/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-20T02:48:47.750Z"
