schema_version: "1.0"
id: chorus_primitive
display_name: Chorus's Primitive Living
short_description: >-
  Mostly things ripped from Primal World, but without sacrificing preexisting
  structures and non-foraged loot. Do not use with Primal World.
description: >-
  Mostly things ripped from Primal World, but without sacrificing preexisting
  structures and non-foraged loot. Do not use with Primal World.
author:
  - Tyzegt
  - ChorusSystem
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/yay855/ChorusMod/tree/main/Chorus Primitive"
version: 2026.6.17-9ba39b3
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-05-16T09:24:48.906Z"
  - version: 2026.6.8-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-08T03:02:20.244Z"
  - version: 2026.6.9-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-09T02:39:08.688Z"
  - version: 2026.6.10-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-10T02:55:53.680Z"
  - version: 2026.6.11-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-11T02:58:44.990Z"
  - version: 2026.6.12-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-12T03:01:45.030Z"
  - version: 2026.6.13-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-13T02:49:03.846Z"
  - version: 2026.6.14-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-14T02:59:32.247Z"
  - version: 2026.6.15-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-15T03:32:48.216Z"
  - version: 2026.6.16-77f71e1
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Primitive
    released_at: "2026-06-16T03:34:48.251Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
  commit_sha: 9ba39b3d1a51b4d743fbb8171079645c918a9854
  extract_path: Chorus Primitive
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/yay855/ChorusMod/77f71e190c6bb430da393eb06ee49f336221715e/Chorus%20Primitive/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-17T03:26:47.070Z"
