schema_version: "1.0"
id: chorus_ma
display_name: Chorus's Martial Arts
short_description: >-
  Custom martial arts styles. Perhaps not the most realistic! Finally balanced a
  bit better.
description: >-
  Custom martial arts styles. Perhaps not the most realistic! Finally balanced a
  bit better.
author:
  - ChorusSystem
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/yay855/ChorusMod/tree/main/Chorus Martial Arts"
version: 2026.6.8-77f71e1
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
  commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
  extract_path: Chorus Martial Arts
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/yay855/ChorusMod/77f71e190c6bb430da393eb06ee49f336221715e/Chorus%20Martial%20Arts/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-08T03:02:56.059Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/yay855/ChorusMod/archive/refs/heads/main.zip"
      commit_sha: 77f71e190c6bb430da393eb06ee49f336221715e
      extract_path: Chorus Martial Arts
    released_at: "2026-05-16T09:24:48.906Z"
