schema_version: "1.0"
id: er_cosplay
display_name: ER Cosplay
short_description: "Adds 14 survivor-inspired hairstyles and Debi/Marlene hats."
author:
  - NakedJake
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/cataclysmroguelikegallery/Cata-Rogall-Modpack/tree/main/BN/ER_cosplay
version: 0.0.0
last_updated: "2026-02-25T03:34:46+09:00"
dependencies:
  bn: ">=0.9.1"
categories:
  - graphics
source:
  type: github_archive
  url: >-
    https://github.com/cataclysmroguelikegallery/Cata-Rogall-Modpack/archive/refs/heads/main.zip
  commit_sha: 2b767bdb800949caa1207d8bb571e9c456ee6dc4
  extract_path: Cata-Rogall-Modpack-main/BN/ER_cosplay
