schema_version: "1.0"
id: fallout_rework
display_name: Fallout New England Remastered
short_description: >-
  Brings a little bit of that retro-futuristic class to the Cataclysm. Guns,
  beasts, and more. Stuff from the Core Region, all the way to the Commonwealth.
  Remade from scratch
author:
  - Tefnut
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Tefnut/Fallout-New-England-Remastered/tree/main/FNE-Remastered
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Tefnut/Fallout-New-England-Remastered/archive/refs/heads/main.zip
  commit_sha: 4f7b45b496e7d3ddf6c8fb12a22b21c25c8f1466
  extract_path: FNE-Remastered
description: >-
  Brings a little bit of that retro-futuristic class to the Cataclysm. Guns,
  beasts, and more. Stuff from the Core Region, all the way to the Commonwealth.
  Remade from scratch
categories:
  - items
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:24:20.452Z"
