schema_version: "1.0"
id: finalfantasymod
display_name: FinalFantasyMod
short_description: >-
  Adds Final Fantasy creatures. When the Catacylsm struck, portals to the Final
  Fantasy Franchise opened, and creatures crossed though. Some friendly, some
  enemy.
description: >-
  Adds Final Fantasy creatures. When the Catacylsm struck, portals to the Final
  Fantasy Franchise opened, and creatures crossed though. Some friendly, some
  enemy.
author:
  - Unknown
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Baratan-creates/BN-FinalFantasyMod/tree/main/FinalFantasyMod
version: 2026.6.8-b206c3f
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/Baratan-creates/BN-FinalFantasyMod/archive/refs/heads/main.zip
  commit_sha: b206c3f1eb1f47eddb50cc427658aa2dc61b06a6
  extract_path: FinalFantasyMod
categories:
  - creatures
modinfo_url: >-
  https://raw.githubusercontent.com/Baratan-creates/BN-FinalFantasyMod/b206c3f1eb1f47eddb50cc427658aa2dc61b06a6/FinalFantasyMod/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-08T03:02:35.746Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Baratan-creates/BN-FinalFantasyMod/archive/refs/heads/main.zip
      commit_sha: b206c3f1eb1f47eddb50cc427658aa2dc61b06a6
      extract_path: FinalFantasyMod
    released_at: "2026-05-16T09:25:20.065Z"
