schema_version: "1.0"
id: fluid_cows
display_name: Fluid Cows
short_description: Adds mutated cows that produce exotic fluids obtained through catalyst cows.
description: Adds mutated cows that produce exotic fluids obtained through catalyst cows.
author:
  - Kota
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/shmakota/Material-Plants/tree/master/Fluid Cows"
version: 2026.6.8-3093665
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip"
  commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
  extract_path: Fluid Cows
categories:
  - items
modinfo_url: >-
  https://raw.githubusercontent.com/shmakota/Material-Plants/309366505af01c607bdd2db28d08b5c2fad98bba/Fluid%20Cows/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: master
last_updated: "2026-06-08T03:02:35.328Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Fluid Cows
    released_at: "2026-05-16T09:25:08.890Z"
