schema_version: "1.0"
id: gawrgura
display_name: Gawr Gura Mutation
short_description: >-
  Adds a shark-girl mutation category inspired by Gawr Gura.  Descend from the
  lost city of Atlantis and embrace your inner apex predator of the seas!
description: >-
  Adds a shark-girl mutation category inspired by Gawr Gura.  Descend from the
  lost city of Atlantis and embrace your inner apex predator of the seas!
author:
  - ihatenumbers
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/ihatenumbers/BN_Gawr_Gura"
version: 2026.6.16-68daf62
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 50c6627e21bab5455cbc06c7fc990489ccebf16c
    released_at: "2026-05-16T09:25:33.708Z"
  - version: 2026.6.8-50c6627
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 50c6627e21bab5455cbc06c7fc990489ccebf16c
    released_at: "2026-06-08T03:02:55.576Z"
  - version: 2026.6.9-50c6627
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 50c6627e21bab5455cbc06c7fc990489ccebf16c
    released_at: "2026-06-09T02:39:46.846Z"
  - version: 2026.6.10-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-10T02:55:51.375Z"
  - version: 2026.6.11-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-11T02:58:38.914Z"
  - version: 2026.6.12-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-12T03:01:42.013Z"
  - version: 2026.6.13-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-13T02:49:00.941Z"
  - version: 2026.6.14-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-14T02:59:26.974Z"
  - version: 2026.6.15-68daf62
    source:
      type: github_archive
      url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
      commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
    released_at: "2026-06-15T03:32:46.369Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/ihatenumbers/BN_Gawr_Gura/archive/refs/heads/main.zip"
  commit_sha: 68daf6210cd729db3663bebfa9766f017654e16f
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/ihatenumbers/BN_Gawr_Gura/50c6627e21bab5455cbc06c7fc990489ccebf16c/modinfo.json
uses_lua: true
lua_api_version: 2
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-16T03:34:45.141Z"
