schema_version: "1.0"
id: gun_bow
display_name: Gunbow
short_description: adds one rare bow with custom-made sound fx
description: adds one rare bow with custom-made sound fx
author:
  - hamatk
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/hamatk/CataclysmBN_Mod_MachineBow/tree/main/gun_bow"
version: 2026.6.17-a7ad0a6
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-05-16T09:25:29.560Z"
  - version: 2026.6.8-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-08T03:03:03.056Z"
  - version: 2026.6.9-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-09T02:39:54.527Z"
  - version: 2026.6.10-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-10T02:55:55.307Z"
  - version: 2026.6.11-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-11T02:58:48.892Z"
  - version: 2026.6.12-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-12T03:01:47.299Z"
  - version: 2026.6.13-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-13T02:49:06.122Z"
  - version: 2026.6.14-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-14T02:59:35.838Z"
  - version: 2026.6.15-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-15T03:32:50.053Z"
  - version: 2026.6.16-a7ad0a6
    source:
      type: github_archive
      url: >-
        https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
      commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
      extract_path: gun_bow
    released_at: "2026-06-16T03:34:50.515Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip
  commit_sha: a7ad0a631fb7dfdd07f6de249971c3699d584509
  extract_path: gun_bow
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/hamatk/CataclysmBN_Mod_MachineBow/a7ad0a631fb7dfdd07f6de249971c3699d584509/gun_bow/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-17T03:26:48.862Z"
