schema_version: "1.0"
id: jackledead_armory_expansion
display_name: "Jackledead Armory: Creeps Goons Guns"
short_description: >-
  Adds creeps, goons, and guns to provide a Survival-FPS-like feel while using
  my armory mod.
description: >-
  Adds creeps, goons, and guns to provide a Survival-FPS-like feel while using
  my armory mod.
author:
  - Jackledead
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/jackledead/jackledead_armory/tree/main/modsBrightNights/jackledead_armory_expansion
version: 2026.6.20-7262ba9
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-05-16T09:25:04.601Z"
  - version: 2026.6.8-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-08T03:02:52.855Z"
  - version: 2026.6.9-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-09T02:39:43.800Z"
  - version: 2026.6.10-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-10T02:55:57.516Z"
  - version: 2026.6.11-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-11T02:58:56.524Z"
  - version: 2026.6.12-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-12T03:01:50.779Z"
  - version: 2026.6.13-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-13T02:49:09.579Z"
  - version: 2026.6.14-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-14T02:59:42.232Z"
  - version: 2026.6.15-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-15T03:32:52.007Z"
  - version: 2026.6.16-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-16T03:34:53.676Z"
  - version: 2026.6.17-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-17T03:26:50.964Z"
  - version: 2026.6.18-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-18T03:01:57.793Z"
  - version: 2026.6.19-7262ba9
    source:
      type: github_archive
      url: >-
        https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip
      commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
      extract_path: modsBrightNights/jackledead_armory_expansion
    released_at: "2026-06-19T03:56:24.763Z"
dependencies:
  bn: ">=0.9.1"
  jackledead_armory: "*"
source:
  type: github_archive
  url: "https://github.com/jackledead/jackledead_armory/archive/refs/heads/main.zip"
  commit_sha: 7262ba982a83f37cb1b12cac58e5f053a44a1833
  extract_path: modsBrightNights/jackledead_armory_expansion
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/jackledead/jackledead_armory/7262ba982a83f37cb1b12cac58e5f053a44a1833/modsBrightNights/jackledead_armory_expansion/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
parent: jackledead_armory
last_updated: "2026-06-20T02:49:11.615Z"
