schema_version: "1.0"
id: lonestweaks
display_name: Lones Augmented Arsenal
short_description: Adds many new atomic gears to BN!
author:
  - Thelonestander
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/thelonestander/Lones-Augmented-Arsenal"
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
  commit_sha: 5dcd7555205af327d926594071a34291ed5e7748
description: Adds many new atomic gears to BN!
categories:
  - content
dependencies:
  bn: ">=0.9.1"
  aftershock: "*"
  cata++: "*"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:25:25.579Z"
