schema_version: "1.0"
id: lones_used_cars
display_name: Lones used cars
short_description: A mod that adds new cars to BN!
author:
  - thelonestander
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/thelonestander/Lones-Used-Cars"
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/thelonestander/Lones-Used-Cars/archive/refs/heads/main.zip
  commit_sha: 492b6c09f627b4cd40d48e453d519641786805d2
description: A mod that adds new cars to BN!
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:25:30.900Z"
