schema_version: "1.0"
id: lonestweaks
display_name: Lones Augmented Arsenal
short_description: Adds many new atomic gears to BN!
description: Adds many new atomic gears to BN!
author:
  - Thelonestander
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/thelonestander/Lones-Augmented-Arsenal"
version: 2026.6.20-3a39625
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 5dcd7555205af327d926594071a34291ed5e7748
    released_at: "2026-05-16T09:25:25.579Z"
  - version: 2026.6.8-2f56566
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 2f56566c26c13fcf5f80b69f2dede100f2fd4da2
    released_at: "2026-06-08T03:02:32.796Z"
  - version: 2026.6.9-5da1285
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 5da128593ef052bf8679061848b197c6b3fca24a
    released_at: "2026-06-09T02:39:21.803Z"
  - version: 2026.6.10-5da1285
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 5da128593ef052bf8679061848b197c6b3fca24a
    released_at: "2026-06-10T02:55:48.072Z"
  - version: 2026.6.11-5da1285
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 5da128593ef052bf8679061848b197c6b3fca24a
    released_at: "2026-06-11T02:58:29.443Z"
  - version: 2026.6.12-5da1285
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 5da128593ef052bf8679061848b197c6b3fca24a
    released_at: "2026-06-12T03:01:37.055Z"
  - version: 2026.6.13-8a98e8e
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 8a98e8e61cd7138279dfec4deb4d625069d38e81
    released_at: "2026-06-13T02:48:56.230Z"
  - version: 2026.6.14-8a98e8e
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 8a98e8e61cd7138279dfec4deb4d625069d38e81
    released_at: "2026-06-14T02:59:18.423Z"
  - version: 2026.6.15-8a98e8e
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 8a98e8e61cd7138279dfec4deb4d625069d38e81
    released_at: "2026-06-15T03:32:43.079Z"
  - version: 2026.6.16-fd39df6
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: fd39df6e59968bd659f6464580ed4707562cce6e
    released_at: "2026-06-16T03:34:40.346Z"
  - version: 2026.6.17-fd39df6
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: fd39df6e59968bd659f6464580ed4707562cce6e
    released_at: "2026-06-17T03:26:41.210Z"
  - version: 2026.6.18-6c36469
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 6c364696500a73608896d764ef1235d8982460ea
    released_at: "2026-06-18T03:01:35.082Z"
  - version: 2026.6.19-6c36469
    source:
      type: github_archive
      url: >-
        https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
      commit_sha: 6c364696500a73608896d764ef1235d8982460ea
    released_at: "2026-06-19T03:56:02.535Z"
dependencies:
  bn: ">=0.9.1"
  aftershock: "*"
  cata++: "*"
source:
  type: github_archive
  url: >-
    https://github.com/thelonestander/Lones-Augmented-Arsenal/archive/refs/heads/main.zip
  commit_sha: 3a39625f2c5d14591edf403462117fbc82268086
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/thelonestander/Lones-Augmented-Arsenal/5dcd7555205af327d926594071a34291ed5e7748/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-20T02:48:59.262Z"
