schema_version: "1.0"
id: materials_plants
display_name: Material Plants
short_description: >-
  Adds mutated plants that grow materials like steel and gold.


  Exhaustive list: aluminum, coal, gold, silver, zinc, tin, lead, copper,
  platinum, bronze, steel, rock, rocksalt, sulfur, limestone, gunpow
author:
  - Broken "Spaghetti" Admin
  - Kota
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/shmakota/Material-Plants/tree/master/Material Plants"
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip"
  commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
  extract_path: Material Plants
description: >-
  Adds mutated plants that grow materials like steel and gold.


  Exhaustive list: aluminum, coal, gold, silver, zinc, tin, lead, copper,
  platinum, bronze, steel, rock, rocksalt, sulfur, limestone, gunpowder, kevlar,
  plastic, and meat.
categories:
  - items
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
last_updated: "2026-05-16T09:25:08.890Z"
