schema_version: "1.0"
id: materials_plants
display_name: Material Plants
short_description: >-
  Adds mutated plants that grow materials like steel and gold.


  Exhaustive list: aluminum, coal, gold, silver, zinc, tin, lead, copper,
  platinum, bronze, steel, rock, rocksalt, sulfur, limestone, gunpow
description: >-
  Adds mutated plants that grow materials like steel and gold.


  Exhaustive list: aluminum, coal, gold, silver, zinc, tin, lead, copper,
  platinum, bronze, steel, rock, rocksalt, sulfur, limestone, gunpowder, kevlar,
  plastic, and meat.
author:
  - Broken "Spaghetti" Admin
  - Kota
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/shmakota/Material-Plants/tree/master/Material Plants"
version: 2026.6.16-3093665
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-05-16T09:25:08.890Z"
  - version: 2026.6.8-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-08T03:02:34.293Z"
  - version: 2026.6.9-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-09T02:39:23.363Z"
  - version: 2026.6.10-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-10T02:55:50.949Z"
  - version: 2026.6.11-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-11T02:58:37.791Z"
  - version: 2026.6.12-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-12T03:01:41.424Z"
  - version: 2026.6.13-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-13T02:49:00.358Z"
  - version: 2026.6.14-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-14T02:59:25.964Z"
  - version: 2026.6.15-3093665
    source:
      type: github_archive
      url: >-
        https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip
      commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
      extract_path: Material Plants
    released_at: "2026-06-15T03:32:45.956Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/shmakota/Material-Plants/archive/refs/heads/master.zip"
  commit_sha: 309366505af01c607bdd2db28d08b5c2fad98bba
  extract_path: Material Plants
categories:
  - items
modinfo_url: >-
  https://raw.githubusercontent.com/shmakota/Material-Plants/309366505af01c607bdd2db28d08b5c2fad98bba/Material%20Plants/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: master
last_updated: "2026-06-16T03:34:44.532Z"
