schema_version: "1.0"
id: more_bandits
display_name: "More Bandits, Testing version"
short_description: >-
  Adds a lot more spawning locations for small groups of bandits making them
  much more frequent.  All code extracted from No_Hope mod by Night_Pryanik
description: >-
  Adds a lot more spawning locations for small groups of bandits making them
  much more frequent.  All code extracted from No_Hope mod by Night_Pryanik
author:
  - SzQ
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/SzQ1/More-Bandits"
version: 2026.6.16-c36d4d8
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-05-16T09:24:19.115Z"
  - version: 2026.6.8-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-08T03:02:39.220Z"
  - version: 2026.6.9-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-09T02:39:28.690Z"
  - version: 2026.6.10-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-10T02:55:49.599Z"
  - version: 2026.6.11-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-11T02:58:34.143Z"
  - version: 2026.6.12-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-12T03:01:39.427Z"
  - version: 2026.6.13-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-13T02:48:58.521Z"
  - version: 2026.6.14-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-14T02:59:22.503Z"
  - version: 2026.6.15-c36d4d8
    source:
      type: github_archive
      url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
      commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
    released_at: "2026-06-15T03:32:44.586Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/SzQ1/More-Bandits/archive/refs/heads/main.zip"
  commit_sha: c36d4d831c63e91d24c73448333fbf1419da32e4
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/SzQ1/More-Bandits/c36d4d831c63e91d24c73448333fbf1419da32e4/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-16T03:34:42.592Z"
