schema_version: "1.0"
id: no_addictions
display_name: No Addictions
short_description: Zeroes out potential for addiction from default comestibles.
description: Zeroes out potential for addiction from default comestibles.
author:
  - Relgar
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Relgar/CBN-No-Addictions/tree/main/No_Addictions"
version: 2026.6.19-70eec83
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-05-16T09:24:27.159Z"
  - version: 2026.6.8-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-08T03:02:28.461Z"
  - version: 2026.6.9-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-09T02:39:17.050Z"
  - version: 2026.6.10-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-10T02:55:55.692Z"
  - version: 2026.6.11-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-11T02:58:49.736Z"
  - version: 2026.6.12-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-12T03:01:47.782Z"
  - version: 2026.6.13-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-13T02:49:06.592Z"
  - version: 2026.6.14-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-14T02:59:36.549Z"
  - version: 2026.6.15-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-15T03:32:50.471Z"
  - version: 2026.6.16-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-16T03:34:50.956Z"
  - version: 2026.6.17-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-17T03:26:49.226Z"
  - version: 2026.6.18-70eec83
    source:
      type: github_archive
      url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
      commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
      extract_path: No_Addictions
    released_at: "2026-06-18T03:01:52.128Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Relgar/CBN-No-Addictions/archive/refs/heads/main.zip"
  commit_sha: 70eec8386256b2c154c7a7ad2efe2459972cf7b0
  extract_path: No_Addictions
categories:
  - rebalance
modinfo_url: >-
  https://raw.githubusercontent.com/Relgar/CBN-No-Addictions/70eec8386256b2c154c7a7ad2efe2459972cf7b0/No_Addictions/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-19T03:56:19.280Z"
