schema_version: "1.0"
id: pm_mr
display_name: PM-Militia Rifleman
short_description: >-
  A civilian militia rifleman, lower tier than a proper soldier. dont use with
  the all in one variant
description: >-
  A civilian militia rifleman, lower tier than a proper soldier. dont use with
  the all in one variant
author:
  - Some Dumbass
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Shad0wBlad321/Profession-Mod/tree/main/Militia Rifleman"
version: 2026.6.20-be2f1f9
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-05-16T09:25:07.173Z"
  - version: 2026.6.8-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-08T03:02:41.190Z"
  - version: 2026.6.9-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-09T02:39:30.978Z"
  - version: 2026.6.10-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-10T02:55:56.040Z"
  - version: 2026.6.11-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-11T02:58:51.859Z"
  - version: 2026.6.12-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-12T03:01:48.581Z"
  - version: 2026.6.13-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-13T02:49:07.343Z"
  - version: 2026.6.14-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-14T02:59:38.323Z"
  - version: 2026.6.15-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-15T03:32:50.745Z"
  - version: 2026.6.16-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-16T03:34:51.667Z"
  - version: 2026.6.17-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-17T03:26:49.534Z"
  - version: 2026.6.18-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-18T03:01:53.884Z"
  - version: 2026.6.19-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Militia Rifleman
    released_at: "2026-06-19T03:56:21.019Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip"
  commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
  extract_path: Militia Rifleman
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Shad0wBlad321/Profession-Mod/be2f1f958c17fbf2a5dbdff05ca45e690533fce5/Militia%20Rifleman/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-20T02:49:09.602Z"
