schema_version: "1.0"
id: pm_p
display_name: PM-Preppers
short_description: "Rebalance bionic prepper and add a normal one, dont use alongside all in one"
description: "Rebalance bionic prepper and add a normal one, dont use alongside all in one"
author:
  - Some Dumbass
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Shad0wBlad321/Profession-Mod/tree/main/Prepper"
version: 2026.6.20-be2f1f9
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-05-16T09:25:07.174Z"
  - version: 2026.6.8-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-08T03:02:40.619Z"
  - version: 2026.6.9-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-09T02:39:30.342Z"
  - version: 2026.6.10-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-10T02:55:48.848Z"
  - version: 2026.6.11-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-11T02:58:32.362Z"
  - version: 2026.6.12-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-12T03:01:38.378Z"
  - version: 2026.6.13-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-13T02:48:57.564Z"
  - version: 2026.6.14-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-14T02:59:20.887Z"
  - version: 2026.6.15-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-15T03:32:43.776Z"
  - version: 2026.6.16-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-16T03:34:41.553Z"
  - version: 2026.6.17-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-17T03:26:42.010Z"
  - version: 2026.6.18-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-18T03:01:37.523Z"
  - version: 2026.6.19-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Prepper
    released_at: "2026-06-19T03:56:04.865Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip"
  commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
  extract_path: Prepper
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Shad0wBlad321/Profession-Mod/be2f1f958c17fbf2a5dbdff05ca45e690533fce5/Prepper/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-20T02:49:00.348Z"
