schema_version: "1.0"
id: pm_rv
display_name: PM-RV
short_description: Replace Shotgun Hunter With RV Owner
description: Replace Shotgun Hunter With RV Owner
author:
  - Some Dumbass
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Shad0wBlad321/Profession-Mod/tree/main/RV Man"
version: 2026.6.8-be2f1f9
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip"
  commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
  extract_path: RV Man
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Shad0wBlad321/Profession-Mod/be2f1f958c17fbf2a5dbdff05ca45e690533fce5/RV%20Man/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-08T03:02:25.090Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: RV Man
    released_at: "2026-05-16T09:25:07.174Z"
