schema_version: "1.0"
id: realdarkskies_secronom_patchmod
display_name: Really Dark Skies plus Secronom
short_description: A patchmod for Really Dark Skies which adds increased support for Secronom
description: A patchmod for Really Dark Skies which adds increased support for Secronom
author:
  - Zlorthishen
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/Really_Dark_Skies/tree/main/Patch_mods/RDS_plus_Secronom
version: 2026.6.16-4e6abff
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-05-16T09:24:59.313Z"
  - version: 2026.6.8-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-08T03:02:40.439Z"
  - version: 2026.6.9-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-09T02:39:30.127Z"
  - version: 2026.6.10-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-10T02:55:37.041Z"
  - version: 2026.6.11-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-11T02:57:58.707Z"
  - version: 2026.6.12-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-12T03:01:20.698Z"
  - version: 2026.6.13-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-13T02:48:41.228Z"
  - version: 2026.6.14-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-14T02:58:50.172Z"
  - version: 2026.6.15-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-06-15T03:32:32.235Z"
dependencies:
  bn: ">=0.9.1"
  realdarkskies: "*"
  secronom: "*"
  secronom_lore_expansion: "*"
source:
  type: github_archive
  url: "https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip"
  commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
  extract_path: Patch_mods/RDS_plus_Secronom
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Zlorthishen/Really_Dark_Skies/4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea/Patch_mods/RDS_plus_Secronom/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
parent: realdarkskies
last_updated: "2026-06-16T03:34:24.792Z"
