schema_version: "1.0"
id: realdarkskies_secronom_patchmod
display_name: Really Dark Skies plus Secronom
short_description: A patchmod for Really Dark Skies which adds increased support for Secronom
description: A patchmod for Really Dark Skies which adds increased support for Secronom
author:
  - Zlorthishen
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/Really_Dark_Skies/tree/main/Patch_mods/RDS_plus_Secronom
version: 2026.6.8-4e6abff
dependencies:
  bn: ">=0.9.1"
  realdarkskies: "*"
  secronom: "*"
  secronom_lore_expansion: "*"
source:
  type: github_archive
  url: "https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip"
  commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
  extract_path: Patch_mods/RDS_plus_Secronom
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Zlorthishen/Really_Dark_Skies/4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea/Patch_mods/RDS_plus_Secronom/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
parent: realdarkskies
last_updated: "2026-06-08T03:02:40.439Z"
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Secronom
    released_at: "2026-05-16T09:24:59.313Z"
