schema_version: "1.0"
id: realdarkskies_faction_warfare
display_name: Really Dark Skies - Stray Casualties
short_description: >-
  A patchmod for Really Dark Skies which changes the bio-crystal 'Stray' zombies
  to be hostile to the Xenoids.
description: >-
  A patchmod for Really Dark Skies which changes the bio-crystal 'Stray' zombies
  to be hostile to the Xenoids.
author:
  - Zlorthishen
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/Really_Dark_Skies/tree/main/Patch_mods/RDS_Faction_Warfare
version: 2026.6.19-4e6abff
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-05-16T09:24:59.306Z"
  - version: 2026.6.8-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-08T03:02:31.505Z"
  - version: 2026.6.9-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-09T02:39:20.560Z"
  - version: 2026.6.10-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-10T02:55:56.799Z"
  - version: 2026.6.11-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-11T02:58:54.317Z"
  - version: 2026.6.12-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-12T03:01:49.731Z"
  - version: 2026.6.13-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-13T02:49:08.551Z"
  - version: 2026.6.14-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-14T02:59:40.330Z"
  - version: 2026.6.15-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-15T03:32:51.329Z"
  - version: 2026.6.16-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-16T03:34:52.669Z"
  - version: 2026.6.17-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-17T03:26:50.265Z"
  - version: 2026.6.18-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_Faction_Warfare
    released_at: "2026-06-18T03:01:55.945Z"
dependencies:
  bn: ">=0.9.1"
  realdarkskies: "*"
source:
  type: github_archive
  url: "https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip"
  commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
  extract_path: Patch_mods/RDS_Faction_Warfare
categories:
  - monster_exclude
modinfo_url: >-
  https://raw.githubusercontent.com/Zlorthishen/Really_Dark_Skies/4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea/Patch_mods/RDS_Faction_Warfare/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
parent: realdarkskies
last_updated: "2026-06-19T03:56:22.964Z"
