schema_version: "1.0"
id: realdarkskies
display_name: Really Dark Skies
short_description: >-
  A supplement mod that increments the Cataclysm Bright Nights experience by
  adding an inscrutable evil, extra-terrestrial humanoid paramilitary
  expeditionary force to your typical survival scenario. /n
author:
  - Zlorthishen
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Zlorthishen/Really_Dark_Skies/tree/main/Really_Dark_Skies"
version: 2026.6.19-4e6abff
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-05-16T09:25:54.228Z"
  - version: 2026.6.8-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-08T03:02:38.224Z"
  - version: 2026.6.9-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-09T02:39:27.591Z"
  - version: 2026.6.10-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-10T02:55:51.171Z"
  - version: 2026.6.11-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-11T02:58:38.400Z"
  - version: 2026.6.12-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-12T03:01:41.716Z"
  - version: 2026.6.13-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-13T02:49:00.651Z"
  - version: 2026.6.14-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-14T02:59:26.481Z"
  - version: 2026.6.15-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-15T03:32:46.138Z"
  - version: 2026.6.16-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-16T03:34:44.871Z"
  - version: 2026.6.17-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-17T03:26:44.493Z"
  - version: 2026.6.18-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Really_Dark_Skies
    released_at: "2026-06-18T03:01:42.537Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip"
  commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
  extract_path: Really_Dark_Skies
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/Zlorthishen/Really_Dark_Skies/4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea/Really_Dark_Skies/modinfo.json
uses_lua: true
lua_api_version: 2
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-19T03:56:09.788Z"
