schema_version: "1.0"
id: swg_sa
display_name: PM-Survivor With A Gun
short_description: >-
  Just a variant of survivor who wasnt so abysmally unprepared, got himself a
  strap before evac. Dont use with the all in one variant.
description: >-
  Just a variant of survivor who wasnt so abysmally unprepared, got himself a
  strap before evac. Dont use with the all in one variant.
author:
  - Some Dumbass
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Shad0wBlad321/Profession-Mod/tree/main/Survivor With A Gun"
version: 2026.6.20-be2f1f9
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-05-16T09:25:07.174Z"
  - version: 2026.6.8-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-08T03:02:37.332Z"
  - version: 2026.6.9-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-09T02:39:26.548Z"
  - version: 2026.6.10-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-10T02:55:39.985Z"
  - version: 2026.6.11-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-11T02:58:06.517Z"
  - version: 2026.6.12-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-12T03:01:25.132Z"
  - version: 2026.6.13-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-13T02:48:45.281Z"
  - version: 2026.6.14-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-14T02:58:57.484Z"
  - version: 2026.6.15-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-15T03:32:35.417Z"
  - version: 2026.6.16-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-16T03:34:29.000Z"
  - version: 2026.6.17-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-17T03:26:33.341Z"
  - version: 2026.6.18-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-18T03:01:16.497Z"
  - version: 2026.6.19-be2f1f9
    source:
      type: github_archive
      url: >-
        https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip
      commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
      extract_path: Survivor With A Gun
    released_at: "2026-06-19T03:55:43.867Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Shad0wBlad321/Profession-Mod/archive/refs/heads/main.zip"
  commit_sha: be2f1f958c17fbf2a5dbdff05ca45e690533fce5
  extract_path: Survivor With A Gun
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Shad0wBlad321/Profession-Mod/be2f1f958c17fbf2a5dbdff05ca45e690533fce5/Survivor%20With%20A%20Gun/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-20T02:48:48.609Z"
