schema_version: "1.0"
id: xl_armors_merchant
display_name: XL Armors for Merchant Mod
short_description: This is an extension that adds XL armors for the Merchant Mod mod.
description: This is an extension that adds XL armors for the Merchant Mod mod.
author:
  - leoCottret
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
version: 2026.6.19-53b55a3
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 57778ad68c1271f1e7069e5c6a0cebdfd40fa01a
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-05-16T09:24:44.652Z"
  - version: 2026.6.8-2e94b3e
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 2e94b3ec069793086efe73923b091a36815c27ae
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-08T03:02:29.226Z"
  - version: 2026.6.9-2e94b3e
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 2e94b3ec069793086efe73923b091a36815c27ae
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-09T02:39:17.958Z"
  - version: 2026.6.10-2e94b3e
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 2e94b3ec069793086efe73923b091a36815c27ae
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-10T02:55:36.475Z"
  - version: 2026.6.11-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-11T02:57:57.674Z"
  - version: 2026.6.12-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-12T03:01:20.079Z"
  - version: 2026.6.13-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-13T02:48:40.630Z"
  - version: 2026.6.14-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-14T02:58:49.224Z"
  - version: 2026.6.15-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-15T03:32:31.684Z"
  - version: 2026.6.16-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-16T03:34:24.123Z"
  - version: 2026.6.17-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-17T03:26:29.220Z"
  - version: 2026.6.18-53b55a3
    source:
      type: github_archive
      url: >-
        https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
      commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
      extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
    released_at: "2026-06-18T03:01:08.774Z"
yanked:
  reason: can re-fit armors into XL
dependencies:
  merchant: "*"
source:
  type: github_archive
  url: >-
    https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
  commit_sha: 53b55a3b6e7fc2632f50111f560f4a72bdb7d13b
  extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant
categories:
  - content
modinfo_url: >-
  https://raw.githubusercontent.com/leoCottret/cbn-leocottret-mods/57778ad68c1271f1e7069e5c6a0cebdfd40fa01a/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Merchant/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-19T03:55:36.377Z"
