schema_version: "1.0"
id: xl_armors_battle_maid
display_name: XL Armors for Battle Maid Redux
short_description: This is an extension that adds XL armors for the Battle Maid Redux mod.
author:
  - leoCottret
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Battle_Maid_Redux
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip
  commit_sha: 57778ad68c1271f1e7069e5c6a0cebdfd40fa01a
  extract_path: MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_Battle_Maid_Redux
description: This is an extension that adds XL armors for the Battle Maid Redux mod.
categories:
  - content
dependencies:
  battle_maid: "*"
autoupdate:
  type: commit
  branch: main
last_updated: "2026-05-16T09:24:44.650Z"
