schema_version: "1.0"
id: xl_clothing
display_name: XL clothing
short_description: >-
  Adds a few winter items for mutants and buffs XL variants of armors to normal
  levels.
description: >-
  Adds a few winter items for mutants and buffs XL variants of armors to normal
  levels.
author:
  - Krwak
license: ALL-RIGHTS-RESERVED
homepage: "https://github.com/Krwak/XL-Clothing/tree/main/XL Clothing"
version: 2026.6.16-c0ebaf2
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-05-16T09:24:51.735Z"
  - version: 2026.6.8-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-08T03:03:00.803Z"
  - version: 2026.6.9-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-09T02:39:52.223Z"
  - version: 2026.6.10-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-10T02:55:54.778Z"
  - version: 2026.6.11-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-11T02:58:47.239Z"
  - version: 2026.6.12-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-12T03:01:46.486Z"
  - version: 2026.6.13-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-13T02:49:05.270Z"
  - version: 2026.6.14-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-14T02:59:34.401Z"
  - version: 2026.6.15-c0ebaf2
    source:
      type: github_archive
      url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
      commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
      extract_path: XL Clothing
    released_at: "2026-06-15T03:32:49.548Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: "https://github.com/Krwak/XL-Clothing/archive/refs/heads/main.zip"
  commit_sha: c0ebaf2de67e3a626ae7008867fe503f0f659db4
  extract_path: XL Clothing
categories:
  - items
modinfo_url: >-
  https://raw.githubusercontent.com/Krwak/XL-Clothing/c0ebaf2de67e3a626ae7008867fe503f0f659db4/XL%20Clothing/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
last_updated: "2026-06-16T03:34:49.692Z"
